# [Ctrl]+[Alt]+[R] で各セクションを実行

### カテゴリ一覧の取得
GET http://localhost:3000/api/categories

### カテゴリの作成
POST http://localhost:3000/api/admin/categories
Content-Type: application/json

{
  "name": "カテゴリ5"
}

### カテゴリの削除
@post_id = b5339748-da65-46e4-9705-ea66f21e0ee2
DELETE http://localhost:3000/api/admin/categories/{{post_id}}

### カテゴリの名前を変更
@post_id = e637c32b-77b8-4297-ad65-debf990eaafb
PUT http://localhost:3000/api/admin/categories/{{post_id}}
Content-Type: application/json

{
  "name": "カテゴリA"
}

### 投稿記事一覧の取得
GET http://localhost:3000/api/posts

### 記事の投稿
POST http://localhost:3000/api/admin/posts
Content-Type: application/json

{
  "title": "投稿X",
  "content": "投稿Xの本文。<br/>投稿Xの本文。投稿Xの本文。",
  "coverImageURL": "https://....",
  "categoryIds": [
    "7e921e0e-cd99-43e4-ba1d-b2f915056cec",
    "360cf665-0efb-442b-9bb4-6bf47633bbed"
  ]
}